### ISSUE TITLE
Include versions in requirements.txt

### ISSUE THREAD

**Issue by halflearned** [gsbDBI/ds-wgan#2]
The current `requirements.txt` file does not specify versions.

However, [this line](https://github.com/gsbDBI/ds-wgan/blob/9dce4eb4856e799efb1b5d813324e7d3c064679f/wgan_model.py#L297) does not run with torch <= 1.0.0. 

The reason is that the output of `max` is a `tuple` in versions 1.0.0 and older, but it is a `namedtuple` in version `1.1.0` and up. The line linked above relies on the output being a `namedtuple`.

**Comment by evanmunro** [comment]
done for torch and tensorboard, thanks
